import os
from dotenv import load_dotenv
import uuid
import asyncio
import logging

load_dotenv()

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.staticfiles import StaticFiles
from fastapi.responses import HTMLResponse
from fastapi.middleware.cors import CORSMiddleware
from conversation_manager.manager import handle_message
from conversation_manager.session_store import (
    reset_session, get_session, cleanup_expired_sessions,
)
from conversation_manager.summary_builder import build_patient_summary
from models.schemas import ChatMessage

app = FastAPI(title="Medical Recovery Companion")
logger = logging.getLogger("medical_bot")

# CORS: allow the Vercel-deployed frontend (or any origin listed in env)
cors_origins = os.getenv("CORS_ORIGINS", "http://localhost:5173,http://localhost:8080").split(",")
app.add_middleware(
    CORSMiddleware,
    allow_origins=[o.strip() for o in cors_origins],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Update paths to point to the built frontend react app (dist instead of raw frontend)
FRONTEND_DIR = os.path.join(os.path.dirname(__file__), "..", "frontend", "dist")

try:
    # Mount the /assets directory generated by vite specifically
    assets_dir = os.path.join(FRONTEND_DIR, "assets")
    if os.path.exists(assets_dir):
        app.mount("/assets", StaticFiles(directory=assets_dir), name="assets")
        
    # Optional: If you have public files like vite.svg
    if os.path.exists(FRONTEND_DIR):
        app.mount("/static", StaticFiles(directory=FRONTEND_DIR), name="static")
except RuntimeError:
    pass

@app.get("/{full_path:path}")
async def serve_react_app(full_path: str):
    # This acts as a catch-all for react-router (e.g. /chat)
    # It always returns the built index.html from Vite
    index_path = os.path.join(FRONTEND_DIR, "index.html")
    if os.path.exists(index_path):
        with open(index_path, encoding='utf-8') as f:
            return HTMLResponse(f.read())
    return HTMLResponse("Frontend isn't built yet. Run 'npm run build' in the frontend dir.", status_code=404)


# ── Background session cleanup ──

async def _session_cleanup_loop():
    """Background task: clean up expired sessions every 5 minutes."""
    while True:
        await asyncio.sleep(300)  # 5 minutes
        try:
            removed = cleanup_expired_sessions()
            if removed:
                logger.info(f"Session cleanup: removed {removed} expired session(s)")
        except Exception as e:
            logger.error(f"Session cleanup error: {e}")


@app.on_event("startup")
async def startup_event():
    """Start background tasks on application startup."""
    asyncio.create_task(_session_cleanup_loop())
    logger.info("Background session cleanup task started (every 5 min)")


@app.post("/session/new")
async def new_session():
    session_id = str(uuid.uuid4())
    return {"session_id": session_id}

@app.post("/session/{session_id}/reset")
async def reset(session_id: str):
    reset_session(session_id)
    return {"status": "reset"}


@app.get("/api/session/{session_id}/summary")
async def get_summary(session_id: str):
    """Get a structured patient recovery summary."""
    session = get_session(session_id)
    patient_state = session.get("patient_state", {})

    summary = build_patient_summary(patient_state)

    return {
        "summary": summary,
        "patient_state": {
            "surgery_type": patient_state.get("surgery_type"),
            "days_post_op": patient_state.get("days_post_op"),
            "pain_current": (
                patient_state["pain_history"][-1]
                if patient_state.get("pain_history") else None
            ),
            "temperature_current": (
                patient_state["temperature_history"][-1]
                if patient_state.get("temperature_history") else None
            ),
            "symptoms": patient_state.get("symptoms", []),
        },
    }


@app.websocket("/ws/chat/{session_id}")
async def websocket_chat(websocket: WebSocket, session_id: str):
    await websocket.accept()
    try:
        while True:
            data = await websocket.receive_text()
            async for chunk in handle_message(session_id, data):
                await websocket.send_text(chunk)
            await websocket.send_text("[END]")  # Signal end of response
    except WebSocketDisconnect:
        pass
