import os
from dotenv import load_dotenv
import uuid

load_dotenv()

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.staticfiles import StaticFiles
from fastapi.responses import HTMLResponse
from conversation_manager.manager import handle_message
from conversation_manager.session_store import reset_session
from models.schemas import ChatMessage

app = FastAPI(title="Medical Recovery Companion")

# Update paths to point to the built frontend react app (dist instead of raw frontend)
FRONTEND_DIR = os.path.join(os.path.dirname(__file__), "..", "frontend", "dist")

try:
    # Mount the /assets directory generated by vite specifically
    assets_dir = os.path.join(FRONTEND_DIR, "assets")
    if os.path.exists(assets_dir):
        app.mount("/assets", StaticFiles(directory=assets_dir), name="assets")
        
    # Optional: If you have public files like vite.svg
    if os.path.exists(FRONTEND_DIR):
        app.mount("/static", StaticFiles(directory=FRONTEND_DIR), name="static")
except RuntimeError:
    pass

@app.get("/{full_path:path}")
async def serve_react_app(full_path: str):
    # This acts as a catch-all for react-router (e.g. /chat)
    # It always returns the built index.html from Vite
    index_path = os.path.join(FRONTEND_DIR, "index.html")
    if os.path.exists(index_path):
        with open(index_path, encoding='utf-8') as f:
            return HTMLResponse(f.read())
    return HTMLResponse("Frontend isn't built yet. Run 'npm run build' in the frontend dir.", status_code=404)


@app.post("/session/new")
async def new_session():
    session_id = str(uuid.uuid4())
    return {"session_id": session_id}

@app.post("/session/{session_id}/reset")
async def reset(session_id: str):
    reset_session(session_id)
    return {"status": "reset"}

@app.websocket("/ws/chat/{session_id}")
async def websocket_chat(websocket: WebSocket, session_id: str):
    await websocket.accept()
    try:
        while True:
            data = await websocket.receive_text()
            async for chunk in handle_message(session_id, data):
                await websocket.send_text(chunk)
            await websocket.send_text("[END]")  # Signal end of response
    except WebSocketDisconnect:
        pass
