import os
from dotenv import load_dotenv
import uuid
import asyncio
import logging

load_dotenv()

from fastapi import FastAPI, WebSocket, WebSocketDisconnect, UploadFile, File
from fastapi.staticfiles import StaticFiles
from fastapi.responses import HTMLResponse, Response
from fastapi.middleware.cors import CORSMiddleware
from conversation_manager.manager import handle_message
from conversation_manager.session_store import (
    reset_session, get_session, cleanup_expired_sessions,
)
from conversation_manager.summary_builder import build_patient_summary
from models.schemas import ChatMessage
from nlp_utils.asr_engine import get_asr_engine
from nlp_utils.tts_engine import get_tts_engine

app = FastAPI(title="Medical Recovery Companion")
logger = logging.getLogger("medical_bot")

# CORS: allow the Vercel-deployed frontend (or any origin listed in env)
cors_origins = os.getenv("CORS_ORIGINS", "http://localhost:5173,http://localhost:8080").split(",")
app.add_middleware(
    CORSMiddleware,
    allow_origins=[o.strip() for o in cors_origins],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Update paths to point to the built frontend react app (dist instead of raw frontend)
FRONTEND_DIR = os.path.join(os.path.dirname(__file__), "..", "Conversational_AI-Frontend", "dist")

try:
    # Mount the /assets directory generated by vite specifically
    assets_dir = os.path.join(FRONTEND_DIR, "assets")
    if os.path.exists(assets_dir):
        app.mount("/assets", StaticFiles(directory=assets_dir), name="assets")
        
    # Optional: If you have public files like vite.svg
    if os.path.exists(FRONTEND_DIR):
        app.mount("/static", StaticFiles(directory=FRONTEND_DIR), name="static")
except RuntimeError:
    pass

@app.get("/health")
async def health_check():
    return {"status": "ok"}

@app.get("/{full_path:path}")
async def serve_react_app(full_path: str):
    # This acts as a catch-all for react-router (e.g. /chat)
    # It always returns the built index.html from Vite
    index_path = os.path.join(FRONTEND_DIR, "index.html")
    if os.path.exists(index_path):
        with open(index_path, encoding='utf-8') as f:
            return HTMLResponse(f.read())
    return HTMLResponse("Frontend isn't built yet. Run 'npm run build' in the frontend dir.", status_code=404)


@app.post("/session/new")
async def new_session():
    session_id = str(uuid.uuid4())
    return {"session_id": session_id}

@app.post("/session/{session_id}/reset")
async def reset(session_id: str):
    reset_session(session_id)
    return {"status": "reset"}


@app.get("/api/session/{session_id}/summary")
async def get_summary(session_id: str):
    """Get a structured patient recovery summary."""
    session = get_session(session_id)
    patient_state = session.get("patient_state", {})

    summary = build_patient_summary(patient_state)

    return {
        "summary": summary,
        "patient_state": {
            "surgery_type": patient_state.get("surgery_type"),
            "days_post_op": patient_state.get("days_post_op"),
            "pain_current": (
                patient_state["pain_history"][-1]
                if patient_state.get("pain_history") else None
            ),
            "temperature_current": (
                patient_state["temperature_history"][-1]
                if patient_state.get("temperature_history") else None
            ),
            "symptoms": patient_state.get("symptoms", []),
        },
    }

@app.post("/api/transcribe")
async def transcribe_audio(file: UploadFile = File(...)):
    """Transcribe an uploaded audio file using Whisper (high accuracy, batch)."""
    try:
        content = await file.read()
        from nlp_utils.whisper_engine import get_whisper_engine
        whisper = get_whisper_engine()
        text = whisper.transcribe(content)
        return {"text": text}
    except Exception as e:
        logger.error(f"Whisper transcription error: {e}")
        return {"text": "", "error": str(e)}

@app.post("/api/tts")
async def text_to_speech(body: dict):
    """Convert text to speech using Piper TTS. Returns WAV audio."""
    text = body.get("text", "")
    if not text.strip():
        return Response(content=b"", media_type="audio/wav", status_code=400)
    try:
        tts = get_tts_engine()
        wav_bytes = tts.synthesize(text)
        if not wav_bytes:
            return Response(content=b"", media_type="audio/wav", status_code=500)
        return Response(content=wav_bytes, media_type="audio/wav")
    except Exception as e:
        logger.error(f"TTS endpoint error: {e}")
        return Response(content=b"", media_type="audio/wav", status_code=500)


import time
import json
import numpy as np

@app.websocket("/ws/asr")
async def websocket_asr(websocket: WebSocket):
    """
    Real-time streaming ASR via WebSocket.
    
    Protocol:
    - Client sends binary frames containing raw 16-bit PCM audio at 16kHz mono.
    - Server sends JSON text frames: {"partial": "..."} for interim results.
    - Server sends {"final": "...", "done": true} when silence timeout (5s) is reached.
    """
    await websocket.accept()
    asr = get_asr_engine()

    if not asr or not asr.recognizer:
        await websocket.send_text(json.dumps({"error": "ASR engine not available"}))
        await websocket.close()
        return

    stream = asr.create_stream()
    last_text = ""
    last_change_time = time.time()
    SILENCE_TIMEOUT = 5.0

    try:
        while True:
            # Wait for audio data with a short timeout to check silence
            try:
                data = await asyncio.wait_for(websocket.receive(), timeout=0.5)
            except asyncio.TimeoutError:
                # No data received — check if we should auto-stop due to silence
                elapsed = time.time() - last_change_time
                if last_text and elapsed >= SILENCE_TIMEOUT:
                    final_text = asr.finish(stream)
                    await websocket.send_text(json.dumps({
                        "final": final_text or last_text,
                        "done": True
                    }))
                    break
                continue

            # Check if client disconnected
            if data["type"] == "websocket.disconnect":
                break

            # Handle text control messages
            if "text" in data:
                msg = data["text"]
                if msg == "STOP":
                    final_text = asr.finish(stream)
                    await websocket.send_text(json.dumps({
                        "final": final_text or last_text,
                        "done": True
                    }))
                    break
                continue

            # Handle binary audio data (raw 16-bit PCM, 16kHz, mono)
            if "bytes" in data:
                audio_bytes = data["bytes"]
                if len(audio_bytes) < 2:
                    continue

                # Convert 16-bit PCM to float32
                samples_int16 = np.frombuffer(audio_bytes, dtype=np.int16)
                samples_float32 = samples_int16.astype(np.float32) / 32768.0

                asr.feed_audio(stream, samples_float32)
                current_text = asr.decode(stream)

                if current_text and current_text != last_text:
                    last_text = current_text
                    last_change_time = time.time()
                    await websocket.send_text(json.dumps({
                        "partial": current_text
                    }))

                # Check silence timeout
                elapsed = time.time() - last_change_time
                if last_text and elapsed >= SILENCE_TIMEOUT:
                    final_text = asr.finish(stream)
                    await websocket.send_text(json.dumps({
                        "final": final_text or last_text,
                        "done": True
                    }))
                    break

    except WebSocketDisconnect:
        pass
    except Exception as e:
        logger.error(f"ASR WebSocket error: {e}")
        try:
            await websocket.send_text(json.dumps({"error": str(e)}))
        except Exception:
            pass


@app.websocket("/ws/chat/{session_id}")
async def websocket_chat(websocket: WebSocket, session_id: str):
    await websocket.accept()
    # Check for eval_mode query parameter
    eval_mode = False
    query_string = str(websocket.scope.get("query_string", b""), "utf-8")
    if "eval_mode=true" in query_string:
        eval_mode = True
    try:
        while True:
            data = await websocket.receive_text()
            async for chunk in handle_message(session_id, data, eval_mode=eval_mode):
                await websocket.send_text(chunk)
            await websocket.send_text("[END]")  # Signal end of response
    except WebSocketDisconnect:
        pass

